# Generated by Django 2.0.3 on 2018-04-04 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('player_2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('round_index', models.PositiveIntegerField(blank=True, help_text='The order of this match in the round (used for positioning).', null=True)),
                ('place', models.CharField(blank=True, help_text='The advertisement of the tournament', max_length=100, null=True)),
                ('player_1_init', models.ForeignKey(blank=True, help_text='Set for first round matches', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_game_match', to='tournament.Team')),
                ('player_2_init', models.ForeignKey(blank=True, help_text='Set for first round matches', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_game_match', to='tournament.Team')),
                ('previous_match_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsequent_match_1', to='matches.Match')),
                ('previous_match_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsequent_match_2', to='matches.Match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournament.Tournament')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
    ]
