# Generated by Django 2.0.3 on 2018-04-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, help_text='Account number', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_ads', models.CharField(blank=True, help_text='The advertisement of the tournament', max_length=100, null=True)),
                ('players', models.ManyToManyField(to='tournament.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The public name of the tournament', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('sport', models.CharField(choices=[('pickleball', 'Pickleball'), ('squash', 'Squash '), ('tennis', 'Tennis'), ('table_tennis', 'Table Tennis')], max_length=200)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('tournament_ads', models.CharField(blank=True, help_text='The advertisement of the tournament', max_length=100, null=True)),
                ('players', models.ManyToManyField(blank=True, help_text='Player or Team', to='tournament.Team')),
            ],
        ),
    ]
